In [26]:
#Question 1
import numpy as np
array=np.random.random(size=(10,1))
print(array)
mean=array.mean()
print(mean)

[[0.51154399]
 [0.3999958 ]
 [0.96913723]
 [0.47360488]
 [0.48597883]
 [0.26709692]
 [0.3646011 ]
 [0.18449559]
 [0.60737944]
 [0.42702827]]
0.4690862044055109


In [27]:
#Question 2
array1=np.random.random(size=(20,1))
print(array1)
var=array1.var()
std=array1.std()
print(var)
print(std)

[[0.2658789 ]
 [0.52491519]
 [0.44189011]
 [0.48841025]
 [0.36648478]
 [0.72313753]
 [0.37141709]
 [0.10698909]
 [0.32567989]
 [0.77127796]
 [0.00432501]
 [0.30969064]
 [0.37728973]
 [0.96086496]
 [0.55703611]
 [0.17681509]
 [0.2064982 ]
 [0.32136639]
 [0.49523858]
 [0.35403302]]
0.04933576314384911
0.2221165530613356


In [28]:
#Question 3
arr=np.random.random(size=(10,20))
arr1=np.random.random(size=(20,25))
arr2=np.matmul(arr,arr1)
print(arr2)
arr2.sum()

[[6.34167524 5.34303947 4.71479789 5.65602587 6.03681599 6.10093195
  5.9160541  7.21887352 5.36385556 5.22294579 4.2849327  4.42191395
  6.75829863 6.42535272 7.39717099 5.91422384 6.7051966  6.17928379
  6.62127389 7.45951054 5.04935158 5.86281868 6.31969609 5.01656485
  5.70929353]
 [4.59123336 4.9892387  3.82975565 4.07649125 5.49502153 4.79053943
  4.18264432 5.91082539 4.85071786 4.38058384 3.28761705 3.94741882
  4.7640741  4.11620564 5.37970164 3.97121662 5.20418426 4.78282208
  5.40578063 5.57453841 3.20306467 4.42573147 5.68361089 3.98842373
  4.59501561]
 [4.62898638 4.36309859 3.16773853 3.82398277 4.4051909  4.06415777
  3.52308395 5.12728201 4.14697613 3.85140606 3.40234903 3.48180947
  4.53155562 4.76744996 4.08956628 3.77205401 4.52156834 4.74312273
  4.4165112  5.839155   3.00806439 3.53087168 4.25697166 3.05034131
  3.84108233]
 [6.22174391 5.81641468 5.15279243 4.96305008 6.57381637 6.24695905
  4.87910045 7.11426283 5.22553171 4.92413709 4.13620758 5.26676378
  5.93

1222.3795489353347

In [87]:
#Question 4
array2=np.random.random(size=(10,1))
print(array2)
print("*"*80)
array3=np.ndarray((10,1))
def func(x):
    return 1/1+ np.exp(-x)
List=list()
List1=list()
for i in range(0,array2.shape[0]):
    List.clear()
    for j in array2[i]:
        List.append(func(j))
    List1.append(List)
array3=np.array(List1)
print(array3)

[[0.48354393]
 [0.36727114]
 [0.61873563]
 [0.72187874]
 [0.19746685]
 [0.60906253]
 [0.96362784]
 [0.05399608]
 [0.40741023]
 [0.94308649]]
********************************************************************************
[[1.38942402]
 [1.38942402]
 [1.38942402]
 [1.38942402]
 [1.38942402]
 [1.38942402]
 [1.38942402]
 [1.38942402]
 [1.38942402]
 [1.38942402]]
